# Generated by Django 2.2.27 on 2022-03-04 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_auto_20220304_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_content_y', to='test_app.TestModel')),
            ],
            options={
                'verbose_name_plural': 'Model Y',
                'ordering': ('-created_at',),
            },
        ),
    ]
